### ISSUE TITLE
Cannot connect to ESPHome dashboard

### ISSUE THREAD

**Issue by Salvora** [esphome/esphome-vscode#33]
I have set up the addon as instructed.
```yaml
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
leave_front_door_open: true
```
I can access the dashboard just fine.
but the vscode extension cannot connect for some reason:
`Cannot connect to ESPHome dashboard. Make sure you can access 'https://ha.home.org:6052/' and have set the option 'leave_front_door_open': true`
dashboard uri:
https://ha.home.org:6052
