### ISSUE TITLE
Pin mode error

### ISSUE THREAD

**Issue by abel-msk** [esphome/esphome-vscode#36]
In according documentation,  next code should be correct:
switch:
    platform: gpio
    name: "PCF8574_1"
    pin:
        number: 1
        inverted: true
        mode:
            input: true

But  validator  got error near "input:true" :   "String value cannot be dictionary or list"

**Comment by glmnet** [comment]
Validation is not part of this extension per se, it uses ESPHome itself for validation. So this might be a problem in documentation.

**Comment by mwolfaardt** [comment]
I've got the same issue while adding gpio for binary_sensor for a Sonoff S20 plug

**Comment by lymbada** [comment]
Also getting the same issue
Version 1.18.0, running on MacOS

```
esphome:
  name: my_test_board
  platform: ESP32
  board: lolin32

binary_sensory:
 - platform: gpio
  id: button_1
  name: "Test Button 1" 
  pin:
    number: 15
    mode: 
      pullup: true
      input: true
```

**Comment by lymbada** [comment]
I have since used the code below, I'm actually not sure what the difference (if any) is, but this does work for my project
```
binary_sensory:
 - platform: gpio
  id: button_1
  name: "Test Button 1" 
  pin:
    number: 15
    mode: INPUT_PULLUP
```
