### ISSUE TITLE
Unexpected exception while reading configuration with git packages

### ISSUE THREAD

**Issue by definitio** [esphome/esphome-vscode#38]
Extension doesn't work when config includes packages from a git repository.
Config example:
```
packages:
  remote_package:
    url: https://github.com/esphome/non-existant-repo
    files: [base.yaml]
```
Notification:
```
[31mERROR Unexpected exception while reading configuration:[0m
```
Log:
```
Validating file:///<path_to_file>/config.yaml
Unexpected data too small: 
'
```
