### ISSUE TITLE
How to configure it when running ESPHome locally?

### ISSUE THREAD

**Issue by distante** [esphome/esphome-vscode#72]
I am having problems understanding how to get the plugin to work when running esphome locally on my mac.

I start ESPHOMe with this docker-compose
```
version: '3.3'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./esphome/config:/config
      - ./esphome/cache:/cache
      - /etc/localtime:/etc/localtime:ro
    restart: never 
    # restart: always
    # --- WINDOWS / LINUX ---

  # privileged: true
  # network_mode: host
    # --- END WINDOWS / LINUX ---

    # --- MACOS ---
    ports:
      - '6052:6052'
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    # --- END MACOS ---
```

How can I let the plugin know that it should take a look at `localhost:6052` to get the info when I open my `esphome/config/device-config.yml` file?

I am running this completely outside of home assistant.
