### ISSUE TITLE
Catch too big display

### ISSUE THREAD

**Issue by mfbehrens99** [esphome/esphome-vscode#77]
The following code defines a display with dimensions 30x810 which is too big for the 200 LED Strip. The esp8266 crashes when it executes this code.

```
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO2
    num_leds: 200
    name: "NeoPixel"
    id: "neopixel"


display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: neopixel
    width: 30
    height: 810
    #rotation: 180°
    update_interval: 16ms
    lambda: |-
          it.print(0, 10, id(roboto), "Hello World!");

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20
```
