### ISSUE TITLE
sgp4x platform not recognized

### ISSUE THREAD

**Issue by MallocArray** [esphome/esphome-vscode#85]
When configuring a yaml with other platform sensors, I can hover over the name and get a popup.

When I have sgp4x defined, hovering does not display any helpful information

```yaml
  - platform: sgp4x
    voc:
      name: "${upper_devicename} VOC Index"
      id: voc
    nox:
      name: "${upper_devicename} NOx Index"
      id: nox
    compensation:  # Remove this block if no temp/humidity sensor present for compensation
      temperature_source: temp
      humidity_source: humidity
```
